version: '3.7'

services:
  dagster:
    env_file:
      - ./.env.prod
    build:
      target: production
    ports:
      - 3000:3000
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    command: dagster dev -h 0.0.0.0 -m report_etl_pipeline

  postgres:
    image: postgres:13.11
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dagster_home:
  postgres_data:
