version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${DAGSTER_NGINX_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/ssl.crt:/etc/nginx/ssl.crt
      - ./nginx/ssl.key:/etc/nginx/ssl.key
    depends_on:
      - dagster

  dagster:
    env_file:
      - ./.env.prod
    build:
      target: production
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    command: dagster dev -h 0.0.0.0 -m report_etl_pipeline

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dagster_home:
  postgres_data:
