version: '3.7'

services:
  dagster:
    build:
      target: production
    ports:
      - 3000:3000
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    command: dagster dev -h 0.0.0.0 -m report_etl_pipeline

volumes:
  dagster_home:
