[project]
name = "radis-etl-tkhd"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [{ name = "Kai Schlamp", email = "kai.schlamp@gmail.com" }]
requires-python = ">=3.14,<3.15"
dependencies = [
    "adit-client>=0.51.0",
    "dagster>=1.13.20",
    "dagster-webserver>=1.13.20",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "pydicom>=3.0.2",
    "python-dotenv>=1.2.3",
    "radis-client>=0.9.0",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "invoke>=3.0.3",
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
    "pyright>=1.1.411",
    "ruff>=0.16.5",
]

[tool.pyright]
ignore = ["**/*.ipynb"]
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = true

[tool.ruff]
line-length = 100
lint.select = ["E", "F", "I", "DJ"]

[tool.dagster]
module_name = "radis_etl_tkhd"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
