[tool.poetry]
name = "report-etl-pipeline"
version = "0.1.0"
description = ""
authors = ["Kai Schlamp <kai.schlamp@gmail.com>"]
readme = "README.md"
packages = [{ include = "report_etl_pipeline" }]

[tool.poetry.dependencies]
python = "^3.11"
dagster = "^1.4.5"
dagster-webserver = "^1.4.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.dagster]
module_name = "report_etl_pipeline"
