[tool.poetry]
name = "report-etl-pipeline"
version = "0.1.0"
description = ""
authors = ["Kai Schlamp <kai.schlamp@gmail.com>"]
readme = "README.md"
packages = [{ include = "report_etl_pipeline" }]

[tool.poetry.dependencies]
python = "^3.11"
dagster = "^1.4.5"
dagster-webserver = "^1.4.5"
adit-client = "^0.2.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
ipython = "^8.14.0"
pyright = "^1.1.323"
ruff = "^0.0.285"
invoke = "^2.2.0"
ipykernel = "^6.25.1"

[tool.ruff]
exclude = ["migrations"]
line-length = 100
select = ["E", "F", "I", "DJ"]

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.dagster]
module_name = "report_etl_pipeline"
