version: "3.8"

services:
  dagster:
    build:
      target: production
    image: report_etl_pipeline_prod:latest
    env_file:
      - ../.env.prod
    volumes:
      - ../dagster_home_prod:/opt/dagster/dagster_home
    restart: always
    deploy:
      replicas: 1

  nginx:
    image: nginx:latest
    ports:
      - "${DAGSTER_NGINX_PORT:-3600}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../.htpasswd:/etc/nginx/.htpasswd
      - ../ssl.crt:/etc/nginx/ssl.crt
      - ../ssl.key:/etc/nginx/ssl.key
    depends_on:
      - dagster
    restart: always
    deploy:
      replicas: 1
